repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear==22.7.1, flake8-builtins==1.5.3, flake8-comprehensions==3.9.0, pep8-naming==0.13.1]

-   repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
    -   id: yesqa
        additional_dependencies: [flake8-bugbear==22.7.1, flake8-builtins==1.5.3, flake8-comprehensions==3.9.0, pep8-naming==0.13.1]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.2
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

-   repo: https://github.com/adamchainz/django-upgrade
    rev: 1.7.0
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.0"]
