[tool.poetry]
name = "django-blasphemy"
version = "0.1.0"
description = ""
authors = ["Ülgen Sarıkavak <ulgensrkvk@gmail.com>"]

[tool.poetry.dev-dependencies]
# Debugging
ipdb = "0.13.9"
ipython = "7.24.1"

# Formatters
black = "21.5b2"
# https://github.com/Instagram/Fixit
fixit = "0.1.3"
shed = "0.3.6"   # Requires an old version of click. Can be updated.

[tool.poetry.dependencies]
python = "3.9.5"
Django = "3.2.4"
django-environ = "0.4.5"
sentry-sdk = "1.1.0"

[build-system]
requires = ["poetry-core>=1.1.6"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py39"]
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
