[tool.poetry]
name = "django-blasphemy"
version = "0.1.0"
description = ""
authors = ["Ülgen Sarıkavak <ulgensrkvk@gmail.com>"]

[tool.poetry.dev-dependencies]
# Debugging
ipdb = "0.13.9"
ipython = "7.27.0"
# Formatters
black = "21.8b0"
fixit = "0.1.4"  # https://github.com/Instagram/Fixit
shed = "0.3.10"  # Requires an old version of click. Can be updated.

[tool.poetry.dependencies]
python = "3.9.7"
Django = "3.2.7"
django-environ = "0.7.0"
GitPython = "3.1.24"
psycopg2-binary = "2.9.1"
sentry-sdk = "1.3.1"

[build-system]
requires = ["poetry-core>=1.1.8"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py39"]
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
