[tool.poetry]
name = "django-blasphemy"
version = "0.1.0"
description = ""
authors = ["Ülgen Sarıkavak <ulgensrkvk@gmail.com>"]

[tool.poetry.dev-dependencies]
# Debugging
ipdb = "0.13.9"
ipython = "8.1.1"
# Formatters
black = "22.1.0"
fixit = "0.1.4"  # https://github.com/Instagram/Fixit
flake8 = "4.0.1"
isort = "5.10.1"
shed = "0.9.2"
# Quality check
pre-commit = "2.17.0"

[tool.poetry.dependencies]
python = "3.10.2"
Django = "4.0.3"
django-admin-interface = "0.19.0"
django-debug-toolbar = "3.2.4"
django-environ = "0.8.1"
django-extensions = "3.1.5"
dj-database-url = "0.5.0"
GitPython = "3.1.27"
gunicorn = "20.1.0"
psycopg2-binary = "2.9.3"
sentry-sdk = "1.5.7"
whitenoise = "6.0.0"

[build-system]
requires = ["poetry-core>=1.1.8"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py310"]
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
