# https://github.com/pre-commit/action

name: Lint with Black

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      with:
        extra_args: black --all-files
