# https://github.com/pre-commit/action

name: flake8

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      with:
        extra_args: flake8 --all-files
